runtime: java17 # or another supported version

instance_class: F2

handlers:
  - url: /gamepicker
    static_dir: gamepicker

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
