[versions]
apiClientVersion = "2.0.0"
oauthClientVersion = "1.34.1"
driveV3Version = "v3-rev20220815-2.0.0"
sheetsVersion = "v4-rev612-1.25.0"

[libraries]
apiClient = { group = "com.google.api-client", name = "google-api-client" , version.ref = "apiClientVersion" }
oauthClient = { group = "com.google.oauth-client", name = "google-oauth-client-jetty" , version.ref = "oauthClientVersion" }
apiServicesDrive = { group = "com.google.apis", name = "google-api-services-drive" , version.ref = "driveV3Version" }
apiServicesSheets = { group = "com.google.apis", name = "google-api-services-sheets", version.ref = "sheetsVersion"}
