[versions]
# embeddedMongoVersion = "4.6.3"
springVersion = "3.3.3"
mockKVersion = "1.13.5"

[libraries]
starterDataMongoDbReactive = { group = "org.springframework.boot", name = "spring-boot-starter-data-mongodb-reactive", version.ref = "springVersion"}
starterWebflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "springVersion" }
jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
# embeddedMongo = { group = "de.flapdoodle.embed", name = "de.flapdoodle.embed.mongo", version.ref = "embeddedMongoVersion" }
devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
starterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springVersion" }
mockK = { group = "io.mockk", name = "mockk", version.ref = "mockKVersion" }
