[versions]
embeddedMongoVersion = "4.6.3"

[libraries]
starterDataMongoDb = { group = "org.springframework.boot", name = "spring-boot-starter-data-mongodb-reactive" }
starterDataMongoDbReactive = { group = "org.springframework.boot", name = "spring-boot-starter-data-mongodb" }
starterWeb = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
jacksonModuleKotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin" }
embeddedMongo = { group = "de.flapdoodle.embed", name = "de.flapdoodle.embed.mongo", version.ref = "embeddedMongoVersion" }
devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
starterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
