ec2:
  instance-map:
    palworld: i-050f4fe2b9ad18c9c
    dsc: i-085706dda5cd3ee43

spring:
  data:
    mongodb:
      username: arbitragexiv-service-user
      uri: mongodb+srv://%s:%s@arbitragexiv.i3nux.mongodb.net/?retryWrites=true&w=majority&appName=arbitragexiv
