name: ktlint check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint_check:
    name: ktlintcheck
    timeout-minutes: 5
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3

      - name: ktlint check
        shell: bash
        run: ./gradlew ktlintCheck
