name: ktlint check

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  DB_PASS: ${{ secrets.DB_PASS }}

jobs:
  lint_check:
    name: ktlintcheck
    timeout-minutes: 5
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ktlint check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
