name: Ktlint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DB_PASS: ${{ secrets.DB_PASS }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  YO_THRESHOLD: ${{ secrets.YO_THRESHOLD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  lint_check:
    name: Ktlint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
