name: PR Validations

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit_tests:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests
        shell: bash
        run: ./gradlew test

  lint_check:
      name: ktlint Check
      timeout-minutes: 5
      runs-on: ubuntu-lates
      steps:
        - uses: actions/checkout@v3

        - name: ktlint check
          shell: bash
          run: ./gradlew ktlintCheck