name: Test All

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  DB_PASS: ${{ secrets.DB_PASS }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  unit_tests:
    name: Unit Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
